[package]
name = "Leancoin"
version = "0.1.0"
description = "Contract to create and manage the Leancoin token"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "leancoin"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dev-dependencies]
test-case = "2.0.0"

[dependencies]
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"