[features]
seeds = false
skip-lint = false

[programs.localnet]
leancoin = "CeFVa5iijJASnRmMCvrHep8wVYRZ3XxAmgXArNJhpjmx"
[programs.devnet]
leancoin = "CeFVa5iijJASnRmMCvrHep8wVYRZ3XxAmgXArNJhpjmx"
[programs.testnet]
leancoin = "CeFVa5iijJASnRmMCvrHep8wVYRZ3XxAmgXArNJhpjmx"
[programs.mainnet]
leancoin = "CeFVa5iijJASnRmMCvrHep8wVYRZ3XxAmgXArNJhpjmx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
